import { Post } from "@/types";
import Head from "next/head";
import Header from "@/components/Header/index";
import Pickup from "@/components/Pickup/index";
import Footer from "@/components/Footer/index";
import UniversalContainer from "@/components/UniversalContainer";

type Props = {
  posts: Post[];
};

export async function getStaticProps() {
  const res = await fetch("http://localhost:3001/api/v1/posts");
  const posts = await res.json();
  return {
    props: {
      posts,
    },
    revalidate: 60 * 60 * 24,
  };
}

export default function Home({ posts }: Props) {
  return (
    <div className="main_content">
      <Head>
        <title>たかブログ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Pickup />
      <UniversalContainer posts={posts} />
      <Footer />
    </div>
  );
}
